version: "2"

services:
  rootca:
    build: .
    entrypoint: /opt/entrypoint.sh
    volumes:
      - rootca:/var/lib/rootca
      - ./certs:/var/lib/rootca/output

volumes:
  rootca:
    external: false
