version: "2.3"

services:
  rootca:
    build:
      context: .
      network: "host"
    network_mode: "none"
    volumes:
      - type: volume
        source: rootca
        target: /var/lib/rootca
      - type: bind
        source: ./certs
        target: /var/lib/rootca/output

volumes:
  rootca:
    external: false
